services:
  mysql:
    image: mysql:8.0
    container_name: scp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scp_db
      MYSQL_USER: scp_user
      MYSQL_PASSWORD: scp_password
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
